#ifndef AST_E_KEYBINDINGS
#define AST_E_KEYBINDINGS

class Input {
	public:
	
		static int K_UNKNOWN;
		static int K_a, K_A;
		static int K_b, K_B;
		static int K_c, K_C;
		static int K_d, K_D;
		static int K_e, K_E;
		static int K_f, K_F;
		static int K_g, K_G;
		static int K_h, K_H;
		static int K_i, K_I;
		static int K_j, K_J;
		static int K_k, K_K;
		static int K_l, K_L;
		static int K_m, K_M;
		static int K_n, K_N;
		static int K_o, K_O;
		static int K_p, K_P;
		static int K_q, K_Q;
		static int K_r, K_R;
		static int K_s, K_S;
		static int K_t, K_T;
		static int K_u, K_U;
		static int K_v, K_V;
		static int K_w, K_W;
		static int K_x, K_X;
		static int K_y, K_Y;
		static int K_z, K_Z;
		static int K_1;
		static int K_2;
		static int K_3;
		static int K_4;
		static int K_5;
		static int K_6;
		static int K_7;
		static int K_8;
		static int K_9;
		static int K_0;
		static int K_RETURN;
		static int K_ESCAPE;
		static int K_BACKSPACE;
		static int K_TAB;
		static int K_SPACE;
		static int K_MINUS;
		static int K_EQUALS;
		static int K_LEFTBRACKET;
		static int K_RIGHTBRACKET;
		static int K_BACKSLASH;
		static int K_NONUSHASH;
		static int K_SEMICOLON;
		static int K_APOSTROPHE;
		static int K_GRAVE;
		static int K_TILD;
		static int K_COMMA;
		static int K_PERIOD;
		static int K_SLASH;
		static int K_CAPSLOCK;
		static int K_F1;
		static int K_F2;
		static int K_F3;
		static int K_F4;
		static int K_F5;
		static int K_F6;
		static int K_F7;
		static int K_F8;
		static int K_F9;
		static int K_F10;
		static int K_F11;
		static int K_F12;
		static int K_PRINTSCREEN;
		static int K_SCROLLLOCK;
		static int K_PAUSE;
		static int K_INSERT;
		static int K_HOME;
		static int K_PAGEUP;
		static int K_DELETE;
		static int K_END;
		static int K_PAGEDOWN;
		static int K_RIGHT;
		static int K_LEFT;
		static int K_DOWN;
		static int K_UP;
		static int K_LCTRL;
		static int K_LSHIFT;
		static int K_LALT;
		static int K_LGUI;
		static int K_RCTRL;
		static int K_RSHIFT;
		static int K_RALT;
		static int K_RGUI;

};
#pragma region Input::*=$
 int Input::K_UNKNOWN = 0;
 int Input::K_a = 4;
 int Input::K_b = 5;
 int Input::K_c = 6;
 int Input::K_d = 7;
 int Input::K_e = 8;
 int Input::K_f = 9;
 int Input::K_g = 10;
 int Input::K_h = 11;
 int Input::K_i = 12;
 int Input::K_j = 13;
 int Input::K_k = 14;
 int Input::K_l = 15;
 int Input::K_m = 16;
 int Input::K_n = 17;
 int Input::K_o = 18;
 int Input::K_p = 19;
 int Input::K_q = 20;
 int Input::K_r = 21;
 int Input::K_s = 22;
 int Input::K_t = 23;
 int Input::K_u = 24;
 int Input::K_v = 25;
 int Input::K_w = 26;
 int Input::K_x = 27;
 int Input::K_y = 28;
 int Input::K_z = 29;
 int Input::K_A = 4;
 int Input::K_B = 5;
 int Input::K_C = 6;
 int Input::K_D = 7;
 int Input::K_E = 8;
 int Input::K_F = 9;
 int Input::K_G = 10;
 int Input::K_H = 11;
 int Input::K_I = 12;
 int Input::K_J = 13;
 int Input::K_K = 14;
 int Input::K_L = 15;
 int Input::K_M = 16;
 int Input::K_N = 17;
 int Input::K_O = 18;
 int Input::K_P = 19;
 int Input::K_Q = 20;
 int Input::K_R = 21;
 int Input::K_S = 22;
 int Input::K_T = 23;
 int Input::K_U = 24;
 int Input::K_V = 25;
 int Input::K_W = 26;
 int Input::K_X = 27;
 int Input::K_Y = 28;
 int Input::K_Z = 29;



 int Input::K_1 = 30;
 int Input::K_2 = 31;
 int Input::K_3 = 32;
 int Input::K_4 = 33;
 int Input::K_5 = 34;
 int Input::K_6 = 35;
 int Input::K_7 = 36;
 int Input::K_8 = 37;
 int Input::K_9 = 38;
 int Input::K_0 = 39;
 int Input::K_RETURN = 40;
 int Input::K_ESCAPE = 41;
 int Input::K_BACKSPACE = 42;
 int Input::K_TAB = 43;
 int Input::K_SPACE = 44;
 int Input::K_MINUS = 45;
 int Input::K_EQUALS = 46;
 int Input::K_LEFTBRACKET = 47;
 int Input::K_RIGHTBRACKET = 48;
 int Input::K_BACKSLASH = 49;
 int Input::K_NONUSHASH = 50;
 int Input::K_SEMICOLON = 51;
 int Input::K_APOSTROPHE = 52;
 int Input::K_GRAVE = 53;
 int Input::K_TILD = 53;
 int Input::K_COMMA = 54;
 int Input::K_PERIOD = 55;
 int Input::K_SLASH = 56;
 int Input::K_CAPSLOCK = 57;
 int Input::K_F1 = 58;
 int Input::K_F2 = 59;
 int Input::K_F3 = 60;
 int Input::K_F4 = 61;
 int Input::K_F5 = 62;
 int Input::K_F6 = 63;
 int Input::K_F7 = 64;
 int Input::K_F8 = 65;
 int Input::K_F9 = 66;
 int Input::K_F10 = 67;
 int Input::K_F11 = 68;
 int Input::K_F12 = 69;
 int Input::K_PRINTSCREEN = 70;
 int Input::K_SCROLLLOCK = 71;
 int Input::K_PAUSE = 72;
 int Input::K_INSERT = 73;
 int Input::K_HOME = 74;
 int Input::K_PAGEUP = 75;
 int Input::K_DELETE = 76;
 int Input::K_END = 77;
 int Input::K_PAGEDOWN = 78;
 int Input::K_RIGHT = 79;
 int Input::K_LEFT = 80;
 int Input::K_DOWN = 81;
 int Input::K_UP = 82;
 int Input::K_LCTRL = 224;
 int Input::K_LSHIFT = 225;
 int Input::K_LALT = 226; /**< alt; option */
 int Input::K_LGUI = 227; /**< windows; command (apple); meta */
 int Input::K_RCTRL = 228;
 int Input::K_RSHIFT = 229;
 int Input::K_RALT = 230; /**< alt gr; option */
 int Input::K_RGUI = 231; /**< windows; command (apple); meta */
#pragma endregion



#endif